name: automated-walk-bike-counter
channels:
  - conda-forge
dependencies:
  - configargparse=0.14
  - fsspec=0.5
  - libtiff=4.0
  - munkres=1
  - opencv=4
  - pillow=6
  - pip=19
  - pykalman=0.9
  - python=3
  - requests=2
  - s3fs
  - tensorflow=1.13
  - tqdm=4
