name: count-machine
channels:
  - conda-forge
dependencies:
  - munkres=1.0.12
  - opencv=4.1.2
  - pillow=6.2.1
  - pip=19.3.1
  - pykalman=0.9.5
  - python=3.6.7
  - tensorflow=1.13.1
  - tqdm=4.36.1
